import Head from 'next/head';
import React, { useContext } from 'react';
import { Display, TextArea, VideoController } from './components';
import Header from './components/Header';
import StartButton from './components/StartButton';
import PlayerProvider, { PlayerContext } from './context/Player';

export default function Home() {
  const { isPlaying } = useContext(PlayerContext);

  return (
    <PlayerProvider>
      <div className="bg-base w-screen h-screen">
        <Head>
          <title>SpeedRead</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        {/* <Header /> */}
        <main className="w-full flex items-center justify-center flex-col h-full">
          <h1 className="text-2xl text-gray-200">SpeedRead</h1>
          {isPlaying ? <Display /> : <TextArea />}
          <StartButton />
          <VideoController/>
        </main>
        <footer className="w-screen py-12 h-12 bg-elevation-1 flex flex-1 justify-center items-center">
          <a
            target="_blank"
            className="cursor-pointer text-gray-500 hover:text-gray-400"
            href="https://github.com/MurilloWolf/speed-read"
          >
            Github project
          </a>
        </footer>
      </div>
    </PlayerProvider>
  );
}
