import Head from 'next/head';
import Image from 'next/image';
import React, { useState } from 'react';
import { Display, TextArea } from './components';
import PlayerProvider from './context/Player';

export default function Home() {
  return (
    <PlayerProvider>
      <div className="bg-base">
        <Head>
          <title>SpeedRead</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main>
          <h1 className="text-2xl text-gray-200">SpeedRead</h1>
        </main>
        <TextArea />
        <Display />
        <footer>
          Powered by{' '}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </footer>
      </div>
    </PlayerProvider>
  );
}
